apiVersion: v1
kind: ReplicationController
metadata:
  name: redis1
  namespace: magic
spec:
  replicas: 1
  selector:
    name: redis1
  template:
    metadata:
      labels:
        name: redis1
    spec:
      hostname: redis1
      containers:
      - name: redis1
        image: redis:4
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis1
  namespace: magic
  labels:
    name: redis1
spec:
  selector:
    name: redis1
  ports:
  - port: 6379
    targetPort: 6379
