apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodbpv
  labels:
    app: mongodb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  rbd:                                                                                                                            
    monitors:                                                                                                                     
    - '10.50.60.15:6789'                                                                                                          
    - '10.50.60.16:6789'                                                                                                          
    - '10.50.60.17:6789'                                                                                                          
    pool: rbd                                                                                                                     
    image: local-mongodb                                                                         
    fsType: ext4                                                                                                                  
    readOnly: false                                                                                                               
    user: admin                                                                                                                   
    secretRef:                                                                                                                    
      name: ceph-secret        
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodbpvc
  namespace: test
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
