apiVersion: v1
kind: Service
metadata:
  name: redis2
  namespace: magic
  labels:
    name: redis2
spec:
  selector:
    name: redis2
  ports:
  - name: redis2
    port: 6379
    targetPort: 6379
    protocol: TCP
