apiVersion: v1
kind: Service
metadata:
  name: redis6
  namespace: magic
  labels:
    name: redis6
spec:
  selector:
    name: redis6
  ports:
  - name: redis6
    port: 6379
    targetPort: 6379
    protocol: TCP
