apiVersion: v1
kind: Service
metadata:
  name: redis1
  namespace: magic
  labels:
    name: redis1
spec:
  selector:
    name: redis1
  ports:
  - name: redis1
    port: 6379
    targetPort: 6379
    protocol: TCP
