apiVersion: v1
kind: Service
metadata:
  name: redis3
  namespace: magic
spec:
  selector:
    app: redis3
  ports:
#  - port: 26379
#    name: sentinel
#    protocol: TCP
#    targetPort: 26379
  - port: 7000
    name: server1
    protocol: TCP
    targetPort: 7000
  - port: 7001
    name: server2
    protocol: TCP
    targetPort: 7001
