apiVersion: v1
kind: Service
metadata:
  name: codis-manage
  namespace: magic
spec:
  type: NodePort
  selector:
    app: codis-manage
  ports:
  - port: 18080
    name: dashboard
    protocol: TCP
    targetPort: 18080
  - port: 11080
    name: admin
    protocol: TCP
    targetPort: 11080
  - port: 19000
    name: proxy
    protocol: TCP
    targetPort: 19000
  - port: 8080
    name: fe
    protocol: TCP
    targetPort: 8080
