apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: magic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zk01
      containers:
      - name: zookeeper
        image: registry.cn-hangzhou.aliyuncs.com/1faith/zookeeper:3.4.11
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: zkvolume
          mountPath: /data/zookeeper
        ports:
        - containerPort: 2181
          name: server
          protocol: TCP
         - containerPort: 2222
           name: trans
           protocol: TCP
         - containerPort: 3333
           name: elect
           protocol: TCP
        env:
        - name: SERVER_ID
          value: "1"
      volumes:
      - name: zkvolume
        emptyDir: {}
